on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x' ]
    name: Build ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Check out libs
        run: git clone https://github.com/harbingerofme/RoR2Libs.git libs
      - run: dotnet restore
      - run: dotnet msbuild /p:Configuration=Release
      - run: |
          mkdir dist
          cp images/icon.png dist/
          cp manifest.json dist/
          sed -e "s|\./images/shot-\(.\)\.png|https://raw.githubusercontent.com/pitassi17/TotalItemCount/master/images/shot-\1.png|" README.md > dist/README.md
          cp TotalItemCount/bin/Release/netstandard2.0/TotalItemCount.dll dist/
      - uses: actions/upload-artifact@v2
        with:
          name: TotalItemCount
          path: dist