on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Check out libs
        run: git clone https://github.com/harbingerofme/RoR2Libs.git libs
      - run: dir
      - run: dotnet msbuild /p:Configuration=Release